### ISSUE TITLE
Add version to the JSON file format

### ISSUE THREAD

**Issue by goneall** [wking/fsf-api#10]
Add an "fsfApiVersion" field to the licenses-full.json and individual license JSON files.

The version should follow the standard [Semantic Versioning](https://semver.org/) pattern and increment the major version whenever an API incompatibility is introduced.

**Comment by wking** [comment]
I don't expect many breaking changes once things settle down here (changes of the magnitude of https://github.com/spdx/license-list-XML#553) should be rare.  But providing for compatibility is good.  I'm currently leaning towards adding JSON-LD markup, but still have a local wrinkle with [index maps][1] that I haven't been able to unravel.  With JSON-LD, folks can consistently translate the layout provided here to whatever they prefer while preserving the same semantics.

[1]: https://www.w3.org/TR/2014/REC-json-ld-20140116/#data-indexing

**Comment by goneall** [comment]
I haven't had much direct experience with JSON-LD, but it is supported by the RDF reader library I'm using for the other formats.  I am a fan of RDF - it definitely helps maintaining compatibility.   I know that Yev's looked into JSON-LD for the SPDX spec itself.  If we went this route, I would probably re-write the deserializing code in the tools to use the RDF library, but that will not be much work.

If it were me, I would just wrap the current data inside a map with a key name that makes sense and add a key/value for the version - simpler approach.  It would, however, be a breaking change from the current format.
