### ISSUE TITLE
Getting the context for licenses-full.json

### ISSUE THREAD

**Issue by goneall** [wking/fsf-api#13]
This is likely related to PR #12  

I'm back to trying to get the LicenseListPublisher to work with the currently produced FSF API at https://wking.github.io/fsf-api/licenses-full.json   The current JSON file does not contain the context - it looks like JSON, not JSON-LD.

I can load the context separately, but would need a reference to an accurate context file.  Can you point me to the context and or produce a licenses-full.json with the context?

**Comment by wking** [comment]
I think this was fixed [when I pushed the `schema` directory to gh-pages][1], but it should certainly be fixed now that #12 and its associated gh-pages changes are live.  Let me know if you still have issues, and we can re-open this (or file new issues).

[1]: https://github.com/wking/fsf-api/pull/12#issuecomment-376282369
