### ISSUE TITLE
Pls. add license

### ISSUE THREAD

**Issue by goneall** [wking/fsf-api#2]
Could you add a license designation for the repo at the top level (e.g. LICENSE file)?  I noticed the SPDX license ID in the source file :) Would just suggest having a top level license would make it easier for contributors and users.

**Comment by wking** [comment]
Good idea.  When I got started, I was concerned about the output data (whose licensing isn't clear to me, at the moment its probably under "fair use").  But with that in a separate branch, I think we can safely declare all of master MIT.  I'll file a PR tonight.

**Comment by wking** [comment]
Closed by f59a98e7e4322377c96d541ff392feee30a5dd11 and 21ae38e9ced21c1240679b53029f518589b887c7.
