### ISSUE TITLE
SPDX full names missing

### ISSUE THREAD

**Issue by davidhedlund** [wking/fsf-api#22]
I need the full names for the SPDX licenses in the JSON file.

**Comment by goneall** [comment]
@davidhedlund Suggest you get the full names of the SPDX licenses from the [SPDX JSON file](https://spdx.org/licenses/licenses.json).  You can correlate with this JSON file using the SPDX ID's.  I realize this is a bit more work programmatically, but the SPDX JSON file is generated from the license-XML and will be more maintained than the fsf-api utility.

**Comment by davidhedlund** [comment]
> @davidhedlund Suggest you get the full names of the SPDX licenses from the [SPDX JSON file](https://spdx.org/licenses/licenses.json). You can correlate with this JSON file using the SPDX ID's. I realize this is a bit more work programmatically, but the SPDX JSON file is generated from the license-XML and will be more maintained than the fsf-api utility.

Thank you very much. I noticed that you are a contributor to this repository. How much time would it take for you to implement this in the FSF-API tool? It is needed to finish our [license list in the Free Software Directory (FSF project)](https://directory.fsf.org/wiki/Free_Software_Directory:SPDX_Group).

**Comment by goneall** [comment]
> Thank you very much. I noticed that you are a contributor to this repository. How much time would it take for you to implement this in the FSF-API tool? It is needed to finish our license list in the Free Software Directory (FSF project).

Since my PR's haven't been merged for over 2 years, I made a fork of this repo at https://github.com/spdx/fsf-api and with the help of other contributors have made several improvements.

I'm very interested in the FSF project mentioned above.  Let's continue the conversation in the [spdx/fsf-api issues](https://github.com/spdx/fsf-api).

**Comment by davidhedlund** [comment]
> > Thank you very much. I noticed that you are a contributor to this repository. How much time would it take for you to implement this in the FSF-API tool? It is needed to finish our license list in the Free Software Directory (FSF project).
> 
> Since my PR's haven't been merged for over 2 years, I made a fork of this repo at https://github.com/spdx/fsf-api and with the help of other contributors have made several improvements.
> 
> I'm very interested in the FSF project mentioned above. Let's continue the conversation in the [spdx/fsf-api issues](https://github.com/spdx/fsf-api).

Sounds promising. Can you please submit this issue there and give me the link?

**Comment by goneall** [comment]
@davidhedlund Added https://github.com/spdx/fsf-api/issues/12

**Comment by davidhedlund** [comment]
> @davidhedlund Added [spdx#12](https://github.com/spdx/fsf-api/issues/12)

Thanks.
